// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtFw2m4PGm9Lx2-Ur-fzQ_OW9KQ7JVIjQ',
    appId: '1:792305100362:web:33818ac7d0cdd54fb068b3',
    messagingSenderId: '792305100362',
    projectId: 'habitdo-98593',
    authDomain: 'habitdo-98593.firebaseapp.com',
    storageBucket: 'habitdo-98593.firebasestorage.app',
    measurementId: 'G-D0HMVW6Y87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkZY4GxmmoXYefrL7NmjRbr_v_AVdhrKQ',
    appId: '1:792305100362:android:94cca130367e3806b068b3',
    messagingSenderId: '792305100362',
    projectId: 'habitdo-98593',
    storageBucket: 'habitdo-98593.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYV9anKAzoTJsXBJUgVqQNYJTaMhCI_dc',
    appId: '1:792305100362:ios:7a6b527cc2ba87ebb068b3',
    messagingSenderId: '792305100362',
    projectId: 'habitdo-98593',
    storageBucket: 'habitdo-98593.firebasestorage.app',
    iosBundleId: 'com.example.habitdo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYV9anKAzoTJsXBJUgVqQNYJTaMhCI_dc',
    appId: '1:792305100362:ios:7a6b527cc2ba87ebb068b3',
    messagingSenderId: '792305100362',
    projectId: 'habitdo-98593',
    storageBucket: 'habitdo-98593.firebasestorage.app',
    iosBundleId: 'com.example.habitdo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtFw2m4PGm9Lx2-Ur-fzQ_OW9KQ7JVIjQ',
    appId: '1:792305100362:web:808136b0128ef499b068b3',
    messagingSenderId: '792305100362',
    projectId: 'habitdo-98593',
    authDomain: 'habitdo-98593.firebaseapp.com',
    storageBucket: 'habitdo-98593.firebasestorage.app',
    measurementId: 'G-31D6MDRLKN',
  );
}
